import "./globals.css";
import { ReactNode } from "react";
import Head from "next/head"; // Import Head from Next.js

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
      </Head>
      <body>{children}</body>
    </>
  );
};

export default RootLayout;
