// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import ClientRoot from "./ClientRoot";
import { html } from "framer-motion/client";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico?v=4",
    apple: "/apple-touch-icon.png?v=4",
    shortcut: "/apple-touch-icon.png?v=4",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
            <div className="relative z-11">
              <ClientRoot>{children}</ClientRoot>
            </div>


      </body>

    </html>

  );
}
