import "./globals.css";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/profile.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/profile.ico" type="image/x-icon" />
      </head>
      <body>{children}</body>
    </html>
    
  );
}
